### ISSUE TITLE
jagged edges

### ISSUE THREAD

**Issue by sstil** [mereed/pebbleface-taller2#2]
Hi

thanks for your efforts, I really like this watchface - but the edges on slanted lines in some digits (like 4 and 7) can look really bad. So I took some time and changed those digits, and changed a bit some other digits to have a more consistent look. I'm not familiar with Git so I've put them in an archive, please take a look: https://www.dropbox.com/s/mq2corfxq3a4dz7/pebbleface-taller2-num.zip?dl=0

Thanks

**Comment by mereed** [comment]
hi,  i'm going to apply aliasing to the digits for pebble time.  should have done this much earlier.  just forgot.  thanks for your numbers  :)

mark

**Comment by mereed** [comment]
just updated.  used anti-aliasing on another watchface instead.
